[package]
name = "component3"
version = "0.1.0"
edition = "2021"

[dependencies]
zerocopy = "0.6.1"
userlib = {path = "../../../../../sys/userlib"}
cortex-m = { version = "0.7", features = ["inline-asm"] }

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "component3"
test = false
bench = false