name = "bthermo-syscalls"
target = "thumbv7em-none-eabihf"
board = "stm32l476rg"
chip = "../../chips/stm32l476rg"
stacksize = 896

[kernel]
name = "bthermo-syscalls"
requires = {flash = 24000, ram = 3072}
#
# For the kernel (and for any task that logs), we are required to enable
# either "itm" (denoting logging/panicking via ARM's Instrumentation Trace
# Macrocell) or "semihosting" (denoting logging/panicking via ARM
# semihosting).  We are biased to ITM because semihosting is excruciatingly
# slow (it is breakpoint based) and has an undesirable failure mode if logging
# output is generated and debugger is not attached (namely, the target stops).
# If one does choose to change this to semihosting for purposes of
# development, be sure to also change it in every task of interest.
#
features = ["itm"]

# ID TASK                       GEN PRI STATE    
#  0 rcc                          0   0 recv
#  1 bthermo                      0   5 recv, notif: bit0(T+464)
#  2 ticker                       0  10 notif: bit31(T+10)
#  3 channel                      0  15 recv, notif: usart-irq(irq13) dma-irq bit31
#  4 bthermo_controller           0  20 wait: reply from channel/gen0
#  5 update                       0  30 wait: reply from channel/gen0
#  6 idle                         0 255 RUNNING

[tasks.rcc]
name = "rcc"
features = ["stm32l476rg"]
priority = 0
max-sizes = {flash = 1024, ram = 1024}
uses = ["rcc"]
start = true

[tasks.bthermo]
name = "bthermo"
features = ["v1"]
priority = 5
max-sizes = {flash = 16384, ram = 4096}
stacksize = 2048
uses = ["gpiob", "i2c1"]
task-slots = ["rcc"]
start = true

[tasks.ticker]
name = "ticker"
priority = 10
max-sizes = {flash = 512, ram = 256}
stacksize = 256
start = true

[tasks.channel]
name = "channel"
features = ["stm32l476rg", "log-itm", "multi-support"]
priority = 15
max-sizes = {flash = 16384, ram = 4096}
stacksize = 2048
uses = ["usart3", "gpioc", "dma1"]
start = true
notifications = ["usart-irq", "dma-irq"]
interrupts = {"usart3.irq" = "usart-irq", "dma1.irq3" = "dma-irq"}
task-slots = ["rcc"]

[tasks.bthermo_controller]
name = "bthermo-controller"
features = []
priority = 20
max-sizes = {flash = 4096, ram = 4096}
stacksize = 2048
task-slots = ["bthermo", "channel"]
start = true

[tasks.update]
name = "update"
features = ["log-itm"]
priority = 30
max-sizes = {flash = 16384, ram = 2048}
stacksize = 1024
start = true
uses = ["flash_interface", "bank2", "iwdg"]
notifications = ["flash-irq"]
interrupts = {"flash_interface.irq" = "flash-irq"}
task-slots = ["channel"]

[tasks.idle]
name = "task-idle"
priority = 255
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true