[component]
id = 3
version = 1
priority = 10
flags = ['START_AT_BOOT']
min_ram = 2048

# USART3
[[regions]]
base_address = '0x40004800'
size = '0x0400' # 1024
attributes = [
    'READ',
    'WRITE',
    'DEVICE'
]
[[interrupts]]
irq = 39    # UART3
notification_mask = '0x00000001'

# GPIOC
[[regions]]
base_address = '0x48000800'
size = '0x0400' # 1024
attributes = [
    'READ',
    'WRITE',
    'DEVICE'
]

# DMA1
[[regions]]
base_address = '0x40020000'
size = '0x0400' # 1024
attributes = [
    'READ',
    'WRITE',
    'DEVICE'
]
[[interrupts]]
irq = 13    # DMA1 - Channel 3
notification_mask = '0x00000002'