[component]
id = 2
version = 1
priority = 0
flags = ['START_AT_BOOT']
min_ram = 256
peripherals = ['rcc']

# RCC
#[[regions]]
#base_address = '0x40021000'
#size = '0x0400' # 1024
#attributes = [
#    'READ',
#    'WRITE',
#    'DEVICE'
#]
