name = "stm32f303re_demo"
board = "stm32f303re"
kernel_ram = 6656
clock_speed = 72000000
strip_panics = true

[components.idle]
features = ["log-itm"]

[components.test_a]
features = ["log-itm"]

[components.test_b]
features = ["log-itm"]

[components.rcc]
features = ["log-itm"]

[components.storage]
features = ["log-itm"]

[components.uart-channel-usb]
features = ["log-itm"]

[components.update]
features = ["log-itm"]