name = "stm32f303re_demo"
board = "stm32f303re"
kernel_ram = 8704
clock_speed = 72000000

[components.idle]
features = []

[components.test_a]
features = []

[components.test_b]
features = []

[components.rcc]
features = []

[components.storage]
features = []

[components.uart-channel-usb]
features = []

[components.update]
features = []