COMPONENT_NAME:=component1
current_dir := $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

dump-hbf:
	../../../../../libs/hbf_lite/tests/simple_read/target/release/hbf_simple_read $(current_dir)/$(COMPONENT_NAME).hbf