name = "bthermo"
board = "stm32l476rg"
kernel_ram = 4096
clock_speed = 80000000
strip_panics = true

[components.idle]
features = []

[components.bthermo]
features = []

[components.bthermo-controller]
features = []

[components.rcc]
features = []

[components.storage]
features = []

[components.uart3-channel]
features = ["multi-support"]

[components.update]
features = ["multi-support"]