name = "stm32l432kc_demo"
board = "stm32l432kc"
kernel_ram = 6656
clock_speed = 80000000
strip_panics = true

[components.idle]
features = ["log-semihosting"]

[components.test_a]
features = ["log-semihosting"]

[components.test_b]
features = ["log-semihosting"]

[components.rcc]
features = ["log-semihosting"]

[components.storage]
features = ["log-semihosting"]

[components.uart-channel]
features = ["log-semihosting"]

[components.update]
features = ["log-semihosting"]