[package]
name = "update"
version = "0.1.0"
edition = "2021"

[features]
log-itm = ["userlib/log-itm"]
log-semihosting = ["cortex-m-semihosting", "userlib/log-semihosting"]

[dependencies]
# The idle task cannot panic, so we deliberately don't request panic-messages
# to keep the binary tiny.
userlib = {path = "../../sys/userlib", features = ["panic-messages"]}
cortex-m = { workspace = true, features = ["inline-asm"] }
channel-api = { path = "../channel-api", features = ["multi-support"]}
static_assertions = "1.1.0"
stm32l4 = { version = "0.15.1", features = ["stm32l4x6"] }
cortex-m-semihosting =  { workspace = true, optional=true}

[build-dependencies]
build-util = {path = "../../build/util"}

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "update"
test = false
bench = false
