[component]
id = 2
version = 2
priority = 10
flags = ['START_AT_BOOT']
min_ram = 2048

[[regions]]
base_address = '0x08000000'
size = '0x1000'
attributes = [
    'READ',
    'WRITE',
]

[[regions]]
base_address = '0x08001000'
size = '0x2000'
attributes = ['DMA']
