name = "stm32f303re_bthermo"
board = "stm32f303re"
kernel_ram = 6144
components = [
    "idle", 
    "rcc", 
    "storage", 
    "uart-channel-multi-bluetooth", 
    "update", 
    "bthermo", 
    "bthermo-controller"
]