[component]
id = 10
version = 1
priority = 1
flags = ['START_AT_BOOT']
min_ram = 4096

# GPIOB
[[regions]]
base_address = '0x48000400'
size = '0x0400' # 1024
attributes = [
    'READ',
    'WRITE',
    'DEVICE'
]

# I2C1
[[regions]]
base_address = '0x40005400'
size = '0x0400' # 1024
attributes = [
    'READ',
    'WRITE',
    'DEVICE'
]