# Needed to actually test if the library builds successfully, as cannot be built natively.
# (Only for testing purposes)
build-test-f303re:
	cargo build --release --target thumbv7em-none-eabihf --features f303re,log-itm
build-test-l432kc:
	cargo build --release --target thumbv7em-none-eabihf --features l432kc,log-semihosting
build-test-l476rg:
	cargo build --release --target thumbv7em-none-eabihf --features l476rg,log-itm