# Needed to actually test if the library builds successfully, as cannot be built natively.
# (Only for testing purposes)
build-test:
	cargo build --release --target thumbv7em-none-eabihf --features f303re