[component]
id = 11
version = 1
priority = 20
flags = ['START_AT_BOOT']
min_ram = 2048

# UART
[[dependencies]]
component_id = 3
min_version = 1
max_version = 0

# bThermo
[[dependencies]]
component_id = 10
min_version = 1
max_version = 0
