[component]
id = 4
version = 1
priority = 20
flags = ['START_AT_BOOT']
min_ram = 8192

# Flash Region
[[regions]]
base_address = '0x08040000'
size = '0x40000' # 262144
attributes = [
    'READ',
    'WRITE',
    'EXECUTE' # Otherwise will mess up with the standard flash region, and the component won't execute
]

# Flash Controller
[[regions]]
base_address = '0x40022000'
size = '0x0400' # 1024
attributes = [
    'READ',
    'WRITE',
    'DEVICE'
]