# Needed to actually test if the library builds successfully, it depends on
# userlib and so cannot be built natively.
# (Only for testing purposes)
build-test:
	cargo build --release --target thumbv7em-none-eabihf