[package]
name = "update-tool"
version = "0.0.2"
edition = "2021"
description = "A tool to update Hubris on L4"

[features]
uart = []
mqtt = []

[dependencies]
serde = {version = "1.0.144", features=["derive"]}
clap = {version = "3.2.19", features = ["derive"]}
bitflags = "1.3.2"
pbr = "1.0.3"
itm = "0.3.1"
signal-hook = "0.3.14"
cfg-if = "1.0.0"
goblin = "0.6.0"
# Serial port dependencies
serialport = "4.2.0"
# MQTT dependencies
rumqttc = "0.17.0"
crossbeam-channel = "0.5.6"