[package]
name = "random_version"
version = "0.1.0"
edition = "2021"

[features]
v1 = []
v2 = []

[dependencies]
# The idle task cannot panic, so we deliberately don't request panic-messages
# to keep the binary tiny.
userlib = {path = "../../sys/userlib", features = ["log-itm"]}
cortex-m = { workspace = true, features = ["inline-asm"] }

[build-dependencies]
build-util = {path = "../../build/util"}

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "random_version"
test = false
bench = false
