build:
	cd modules/component_builder && $(MAKE) build
	cd modules/elf2hbf && $(MAKE) build
	cd modules/system_builder && $(MAKE) build
	cd modules/update_tool && $(MAKE) build
	cd scripts/relocations && pip3 install -r requirements.txt